# Generated by Django 3.0.3 on 2021-08-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitycosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='target_year',
            field=models.CharField(default=2021, max_length=4, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='gas',
            name='target_year',
            field=models.CharField(default=2021, max_length=4, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='water',
            name='target_year',
            field=models.CharField(default=2021, max_length=4, verbose_name='年'),
        ),
    ]
