# Generated by Django 3.0.3 on 2021-08-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitycosts', '0002_auto_20210826_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='date_from',
            field=models.DateField(null=True, verbose_name='使用終了日'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='date_to',
            field=models.DateField(null=True, verbose_name='使用開始日'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='date_from',
            field=models.DateField(null=True, verbose_name='使用終了日'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='date_to',
            field=models.DateField(null=True, verbose_name='使用開始日'),
        ),
        migrations.AlterField(
            model_name='water',
            name='date_from',
            field=models.DateField(null=True, verbose_name='使用終了日'),
        ),
        migrations.AlterField(
            model_name='water',
            name='date_to',
            field=models.DateField(null=True, verbose_name='使用開始日'),
        ),
    ]
